### ISSUE TITLE
Please don't DM me when I close a related issue myself

### ISSUE THREAD

**Issue by kipz** [atomist/lifecycle-automation#185]

**Comment by cdupuis** [comment]
I haven't done any DM logic for closing related issues. Could you be a bit more specific what you have seen?

**Comment by kipz** [comment]
![screenshot from 2018-03-19 10-46-13](https://user-images.githubusercontent.com/1865026/37591254-ced969c6-2b62-11e8-839e-596fcb15aa5d.png)

**Comment by kipz** [comment]
I guess this is a general lifecycle thing then?

**Comment by cdupuis** [comment]
I guess so. The problem here is that you triggered the action to close the related issue but the bot is commenting. So lifecycle lost track of the fact that you initiated the closing. We wouldn't DM you if you mentioned yourself. But that isn't the case here. I have to see what we can do here. Maybe just ignore the comment via a special marker.

**Comment by kipz** [comment]
It would be nice if in this instance, it used my personal token, and it wasn't done by the bot! (cc @slimslenderslacks )
