### ISSUE TITLE
Link issue could present drop downs (defaulting to current owner) for repo, owner and issue

### ISSUE THREAD

**Issue by kipz** [atomist/lifecycle-automation#187]
Currently we have repo, owner and issue number requested in a thread. In general, the owner will be the same as the current issue (so we could just default that). But I never know the issue number. Ideally a search-as-you-type box would appear :) But anything that helps me find and link the right issue without having to remember (or type) anything would really help.

**Comment by tanya-coding** [comment]
We do have mapped params for owner (I would expect this already to default to single owner if channel is linked or team only has one owner) and another one for repo but you would only see drop down if there are less than 100 repos, otherwise we fall back to simple question. I don't think there is a great way to present really large number of items using drop downs.. :(

**Comment by cdupuis** [comment]
What are those parameters @tanya-coding? Note, those shouldn’t be bound to what repos are lifecycle linked.

**Comment by tanya-coding** [comment]
@cdupuis  for repo we have `atomist://github/repository?all=true` This param will show all repos for a selected owner. We don't have "all=true" for owner mapped param, so owner mapped param `atomist://github/repository/owner` would still default to single linked/team owner or will present dropdown with team owners if single owner cannot be determined. If we want need to always present all team owners regardless of channel links, it would be easy to add: `atomist://github/repository/owner?all=true`. Let me know if you need that and I'll add an issue in bot for that.

**Comment by cdupuis** [comment]
What if there’s one repo mapped? Would that still show the owner drop down if multiple orgs are enrolled?

**Comment by tanya-coding** [comment]
For owner mapped param, if we add "all=true" it would ask if there are more than one team orgs regardless of any existing channel mappings and default to owner if there is only one for the team. 

If you want it to default based on channel mappings, just omit "all=true" (currently supported option). This only defaults when there is a single option available: either multiple team orgs but all mapped repos are from a single org OR single mapped repo OR single team org.

**Comment by cdupuis** [comment]
Actually on reading this again, I think we need this `atomist://github/repository/owner?all=true` mapped parameter. So please open an issue in the bot for this.

Additional question: What if I have two sets of org/repo, one that should be populated from a mapped repo and one should be based on drop-downs, would that work with you're proposal?

**Comment by tanya-coding** [comment]
Having both will work but we might need to tweak question that bot presents (in case it needs to ask both). Right now bot uses user friendly parameter descriptions (provided by bot) which would be exactly the same for both "all=true" and non "all=true" versions of the parameter. This would be super confusing since user cannot really tell them apart. But in theory your automation could provide custom description (I'm pretty sure bot will just use your description when it's available but we should test that :) ) so I would recommend adding descriptions to those mapped parameters so you can make them for example "target owner/repository" and "source owner/repository".

**Comment by tanya-coding** [comment]
One caveat with having both variations of owner parameter, we won't be able to support `atomist://github/repository/provider` or any other provider related parameters unless both owners are for the same provider.

**Comment by tanya-coding** [comment]
Actually having 2 owners is problematic. Bot won't know which owner to use for either of the two repo parameters.

**Comment by tanya-coding** [comment]
It would be nice to be able to do something like
```
    @MappedParameter("atomist://github/repository?all=true")
    public targetOwner: string;

    @MappedParameter("atomist://github/repository/owner?all=true", owner: "targetOwner")
    public targetRepo: string;

    @MappedParameter(MappedParameters.GitHubRepository, owner: "owner")
    public repo: string;

    @MappedParameter(MappedParameters.GitHubOwner)
    public owner: string;
```

**Comment by cdupuis** [comment]
This is in prod now with only using logic in lifecycle. I think this is the way forward as those mapped parameters make it really hard to port things to the dashboard.
