### ISSUE TITLE
Support simple build workflows when displaying builds

### ISSUE THREAD

**Issue by ddgenome** [atomist/lifecycle-automation#7]
We will be enhancing the Build event to have a workflow ID and relationships to upstream build jobs. This means for each push there can be multiple build events that are distinct but related.

We should have an option to display each build separately or display each "stage" of this build as a single status, where a stage is all jobs with the same upstream jobs. Each stage should show red if any jobs at a stage are failed, yellow if any known jobs at that stage are running, and green if all known jobs are completed successfully. Determining the status of all sibling jobs will likely require a query separate from the event subscription.

On CircleCI workflow builds, the combined build message should have a link to the workflow rendering on the CircleCI site.

**Comment by claymccoy** [comment]
Stage is a group of jobs that all have the exact same upstream jobs. In the CircleCI UI this would be shown as a column, but other than that it doesn't appear that this is an abstraction that CircleCI actually has. So are we putting an abstraction in place that doesn't exist? This seems unnecessary and problematic with no real pay off. For example, what do you call the stage since only its jobs are named, how do you link to it, status of a stage (as described in the issue) seems confusing from a user standpoint. What is pushing this requirement for stages?

"Determining the status of all sibling jobs will likely require a query separate from the event subscription."
Event handlers doing queries seems like an antipattern. The value of the cortex is to have the related information already queried and at your fingertips when the event comes in.

I don't think that we are going to rerender any nicer than the workflow rendering so linking to that makes sense. I don't see any reason to abstract into stages. I'd recommend we keep with core CircleCI concepts. What I would like to see as a user is the current status which is an updated list of the current jobs running and a list of any failed jobs with links directly to those jobs. If I had more questions about how the jobs were related or what the overall progression of the job was then I would follow the link to the workflow rendering on the CircleCI site. A stage wouldn't help me with any of that. It seems like a useless partial abstraction that hides information about the lower level jobs and gives little extra insight into the higher level workflow.

**Comment by whostolebenfrog** [comment]
@claymccoy I _think_ that's a consensus on stages then -> https://github.com/atomisthq/neo4j-ingester/issues/233

Having looked at the workflow stuff this morning (not working properly for some reason...) I'm inclined to agree. I think we can model this quite simply, my only real question is how we send through the parent job ids. I don't _think_ they are part of the payload by default. Not sure what sort of flexibility we have there.

**Comment by ddgenome** [comment]
@claymccoy I think you are correct in that a "stage" is not something CircleCI thinks of as a first class entity. Similarly, I don't think it is something we need to model at all. Rather, it is something that "falls out" naturally from the proposed model, specifically connecting a build with all its upstream builds. We only care about it at all as part of displaying multiple builds within a single workflow. And when I say "we", I mean our customers, who are driving this feature request. Without these or similar enhancements, for each push we either overwrite a single build status for each job within the workflow or render dozens of commit statuses.

@whostolebenfrog I have not looked into what is the default payload provided by CircleCI. We may need to resort to `curl` if their default payload does not have everything we need. I think the minimum we need would be:

-   CIRCLE_WORKFLOW_JOB_ID: the actual unique job name used to link jobs together
-   CIRCLE_BUILD_NUM: simple build number
-   CIRCLE_WORKFLOW_UPSTREAM_JOB_IDS: comma-separated list of CIRCLE_WORKFLOW_JOB_IDs
-   CIRCLE_PROJECT_USERNAME: repo owner
-   CIRCLE_BRANCH: branch being built
-   CIRCLE_BUILD_URL: so we can provide a link
-   CIRCLE_WORKFLOW_ID: while not strictly necessary, it may make querying easier/more efficient
-   CIRCLE_SHA1: commit SHA
-   CIRCLE_PROJECT_REPONAME: repo name

Nice to have:

-   CIRCLE_JOB: displayable name for job

Typical environment for CircleCI job:

```
CIRCLE_WORKFLOW_JOB_ID=d0731dbb-b959-4cbc-9d31-fda7e9551f7b
CIRCLE_BUILD_NUM=15
NODE_VERSION=8.4.0
HOSTNAME=362c0f1b746e
CIRCLE_NODE_TOTAL=1
CIRCLE_INTERNAL_SCRATCH=/tmp/circleci-630031141
CIRCLE_WORKFLOW_UPSTREAM_JOB_IDS=e6d306d0-92bf-48e4-8ad7-94e9a7726d4e,c8bd5af6-9e72-43c6-9319-f352f1e02a49,d5b6b3aa-80c3-474d-8367-138597568ae3,c3c16f20-5488-442f-ad37-8bf388573ff7,7200a83e-ed1c-4215-bfc2-1eed82e2f394,8c9aae26-da9e-445d-92b2-9cc5d9686aff,fcc773fa-2927-436
f-8dc3-578451b1c49b,060d15b3-bc1b-41be-9873-62a9bd849d30,129974f6-c377-4b87-bec3-d3e0621c866e,f1f622f1-817e-4ba7-945d-4e0fed501189,fcedeb77-ef40-44f5-ba0a-1feae10957d9,2a11aeb9-eaf5-462c-bc30-552db562d041,0e69c2d8-f60d-4d68-8ed7-78260a3a224b
CIRCLE_PROJECT_USERNAME=atomisthqa
CIRCLE_WORKFLOW_CONCURRENCY_MAP={"fcedeb77-ef40-44f5-ba0a-1feae10957d9":["f1f622f1-817e-4ba7-945d-4e0fed501189"],"f1f622f1-817e-4ba7-945d-4e0fed501189":["fcedeb77-ef40-44f5-ba0a-1feae10957d9","2a11aeb9-eaf5-462c-bc30-552db562d041"],"2a11aeb9-eaf5-462c-bc30-552db562d041":[
"f1f622f1-817e-4ba7-945d-4e0fed501189"],"c3c16f20-5488-442f-ad37-8bf388573ff7":["7200a83e-ed1c-4215-bfc2-1eed82e2f394","d5b6b3aa-80c3-474d-8367-138597568ae3","c8bd5af6-9e72-43c6-9319-f352f1e02a49"],"060d15b3-bc1b-41be-9873-62a9bd849d30":["fcc773fa-2927-436f-8dc3-578451b1c
49b"],"d5b6b3aa-80c3-474d-8367-138597568ae3":["7200a83e-ed1c-4215-bfc2-1eed82e2f394","c3c16f20-5488-442f-ad37-8bf388573ff7","c8bd5af6-9e72-43c6-9319-f352f1e02a49"],"7200a83e-ed1c-4215-bfc2-1eed82e2f394":["c3c16f20-5488-442f-ad37-8bf388573ff7","d5b6b3aa-80c3-474d-8367-1385
97568ae3","c8bd5af6-9e72-43c6-9319-f352f1e02a49"],"c8bd5af6-9e72-43c6-9319-f352f1e02a49":["7200a83e-ed1c-4215-bfc2-1eed82e2f394","c3c16f20-5488-442f-ad37-8bf388573ff7","d5b6b3aa-80c3-474d-8367-138597568ae3"],"fcc773fa-2927-436f-8dc3-578451b1c49b":["060d15b3-bc1b-41be-9873
-62a9bd849d30"]}
CIRCLE_INTERNAL_TASK_DATA=/.circleci-task-data
NPM_CONFIG_LOGLEVEL=info
NO_PROXY=circleci-internal-outer-build-agent
CIRCLE_NODE_INDEX=0
CIRCLE_COMPARE_URL=https://github.com/atomisthqa/handlers/compare/e3a1d99900de...1926ab0055cf
CIRCLE_BRANCH=master
SSH_AUTH_SOCK=/tmp/circleci-630031141/ssh_auth_sock
CIRCLE_JOB=promote
CIRCLE_WORKING_DIRECTORY=~/project
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
CIRCLE_WORKFLOW_WORKSPACE_ID=c493ac93-5a85-4177-9f11-f227fba06e16
CIRCLE_USERNAME=ddgenome
CIRCLE_PREVIOUS_BUILD_NUM=14
PWD=/home/circleci/project
CIRCLE_STAGE=promote
LANG=C.UTF-8
CIRCLE_BUILD_URL=https://circleci.com/gh/atomisthqa/handlers/15
CIRCLE_WORKFLOW_ID=c493ac93-5a85-4177-9f11-f227fba06e16
CIRCLECI=true
SHLVL=1
HOME=/home/circleci
YARN_VERSION=0.27.5
CIRCLE_SHA1=1926ab0055cfed34866621341dbbb49ebb25af3e
CI=true
CIRCLE_REPOSITORY_URL=git@github.com:atomisthqa/handlers.git
CIRCLE_INTERNAL_CONFIG=/.circleci-runner-config.json
BASH_ENV=/tmp/.bash_env-59df79663391e300015994c4-0-build
CIRCLE_SHELL_ENV=/tmp/.bash_env-59df79663391e300015994c4-0-build
DEBIAN_FRONTEND=noninteractive
CIRCLE_PROJECT_REPONAME=handlers
```

**Comment by whostolebenfrog** [comment]
I've just put together a project to see what gets sent. Looks like there is a lot more info than I realised from looking at some previous examples in our logs. Looks like when using a workflow we might get the info we need.

```edn
{:payload {:has_artifacts true, :previous_successful_build {:build_num 12, :status "success", :build_time_millis 1769}, :context_ids [], :build_parameters {:CIRCLE_JOB "test"}, :usage_queued_at "2017-10-24T13:03:18.864Z", :canceler nil, :committer_name "Ben Griffiths", :owners ["whostolebenfrog"], :infrastructure_fail false, :circle_yml {:string "version: 2\njobs:\n  build:\n    docker:\n      - image: circleci/node:8.4\n    working_directory: ~/repo\n    steps:\n      - checkout\n      - run: env\n  one0:\n    docker:\n      - image: circleci/node:8.4\n    steps:\n      - run: env\n  one1:\n    docker:\n      - image: circleci/node:8.4\n    steps:\n      - run: env\n  test:\n    docker:\n      - image: circleci/node:8.4\n    steps:\n      - run: env\n  promote:\n    docker:\n      - image: circleci/node:8.4\n    steps:\n      - run: env\n\nworkflows:\n  version: 2\n  cd_pipeline:\n    jobs:\n      - build\n      - one0:\n          requires:\n            - build\n      - one1:\n          requires:\n            - build\n      - test:\n          requires:\n            - one0\n            - one1\n\nnotify:\n  webhooks:\n    - url: https://webhook-staging.atomist.services/atomist/circle/teams/T1L0VDKJP\n"}, :all_commit_details [{:commit_url "https://github.com/atomisthqa/ben-circle-workflow-test/commit/9986379ce91b0439059c5a09be4b8a200e8d3033", :committer_name "Ben Griffiths", :committer_email "ben@atomist.com", :author_date "2017-10-24T14:02:45+01:00", :author_login "whostolebenfrog", :committer_login "whostolebenfrog", :commit "9986379ce91b0439059c5a09be4b8a200e8d3033", :author_name "Ben Griffiths", :author_email "ben@atomist.com", :committer_date "2017-10-24T14:02:45+01:00", :branch "master", :body "", :subject "Fix webhook url"}], :why "github", :parallel 1, :ssh_disabled true, :retries nil, :committer_email "ben@atomist.com", :job_name nil, :vcs_tag nil, :username "atomisthqa", :start_time "2017-10-24T13:03:21.279Z", :steps [{:name "Spin up Environment", :actions [{:allocation_id "59ef3a165d63e9000190d101-0-build/3965C4D0", :infrastructure_fail nil, :index 0, :continue nil, :parallel true, :name "Spin up Environment", :start_time "2017-10-24T13:03:21.279Z", :background false, :timedout nil, :type "test", :insignificant false, :end_time "2017-10-24T13:03:22.501Z", :canceled nil, :status "success", :run_time_millis 1222, :truncated false, :has_output true, :bash_command nil, :step 0, :failed nil, :exit_code nil}]} {:name "env", :actions [{:allocation_id "59ef3a165d63e9000190d101-0-build/3965C4D0", :infrastructure_fail nil, :index 0, :continue nil, :parallel true, :name "env", :start_time "2017-10-24T13:03:22.577Z", :background false, :timedout nil, :type "test", :insignificant false, :end_time "2017-10-24T13:03:22.582Z", :canceled nil, :status "success", :run_time_millis 5, :truncated false, :has_output true, :bash_command "#!/bin/bash -eo pipefail\nenv", :step 101, :failed nil, :exit_code 0}]}], :build_num 13, :is_first_green_build false, :timedout false, :stop_time "2017-10-24T13:03:22.582Z", :author_date "2017-10-24T14:02:45+01:00", :build_time_millis 1303, :vcs_type "github", :outcome "success", :lifecycle "finished", :node nil, :picard {:build_agent {:image nil, :properties {:build_agent "0.0.4426-1f716aa", :executor "docker"}}, :resource_class {:cpu 2.0, :ram 4096, :class "medium"}}, :workflows {:job_name "test", :job_id "d03a3dcc-41c2-435f-87d1-f036da75ef45", :workflow_id "f37a4c09-e779-4a36-a6ea-9193c9eb4b55", :workspace_id "f37a4c09-e779-4a36-a6ea-9193c9eb4b55", :upstream_job_ids ["0c0a5bc1-cef9-4694-92c6-7cd46f79156c" "46dcded5-e935-4958-92de-2a934a6e58c3" "8fc940b5-f94c-438a-8a06-9e3adf759b12"], :upstream_concurrency_map {:8fc940b5_f94c_438a_8a06_9e3adf759b12 ["46dcded5-e935-4958-92de-2a934a6e58c3"], :46dcded5_e935_4958_92de_2a934a6e58c3 ["8fc940b5-f94c-438a-8a06-9e3adf759b12"]}, :workflow_name "cd_pipeline"}, :vcs_revision "9986379ce91b0439059c5a09be4b8a200e8d3033", :canceled false, :build_url "https://circleci.com/gh/atomisthqa/ben-circle-workflow-test/13", :pull_requests [], :all_commit_details_truncated false, :messages [], :vcs_url "https://github.com/atomisthqa/ben-circle-workflow-test", :status "success", :previous {:build_num 12, :status "success", :build_time_millis 1769}, :retry_of nil, :compare "https://github.com/atomisthqa/ben-circle-workflow-test/compare/c000f2fcc256...9986379ce91b", :author_name "Ben Griffiths", :author_email "ben@atomist.com", :fail_reason nil, :committer_date "2017-10-24T14:02:45+01:00", :ssh_users [], :oss true, :branch "master", :reponame "ben-circle-workflow-test", :body "", :queued_at "2017-10-24T13:03:18.883Z", :user {:is_user true, :login "whostolebenfrog", :avatar_url "https://avatars2.githubusercontent.com/u/1108776?v=4", :name "Ben Griffiths", :vcs_type "github", :id 1108776}, :subject "Fix webhook url", :dont_build nil, :failed false, :platform "2.0", :no_dependency_cache false}, "atomist-type" "circle", "x-github-teamid" "T1L0VDKJP", "x-atomist-teamid" "T1L0VDKJP"}
```

**Comment by whostolebenfrog** [comment]
So yes, that looks to have everything we need. I note that it appears as though it will send us all the commits from the push. I think we can make this work pretty easily. Good stuff.

Circle was pretty painful to setup though. It kept refusing to refresh things or believe that I had defined a workflows section in my config.yaml. Very frustrating.

**Comment by ddgenome** [comment]
Sorry, I should have pointed you to:

https://github.com/atomisthqa/handlers/blob/master/.circleci/config.yml
https://circleci.com/gh/atomisthqa

We should also record `:start_time` and `:stop_time` if possible. Customers are interested in build timings too. Specifically, they'd like to know the longest build at each "stage" and the total duration for each stage.

**Comment by whostolebenfrog** [comment]
I looked at those but I didn't want to add the webhook to that as we already have travis webhooks for that project. So I copied the config and simplified it a bit for a test project. It was just that circle wasn't playing ball. Eventually it decided what I had was fine, it just took a long time. A few bugs in their system I think.

Yeah we can add timings no problem.

**Comment by claymccoy** [comment]
Yesterday I got a chance to talk to the customer about the representation of the workflow that he would like to see. He is concerned with the overall progress of the job and it should be in a concise format. He is also concerned with seeing red flags like jobs that take a long time or failures. For anything else he wants to be able to click through and see the actual representation on CircleCI.

**Comment by claymccoy** [comment]
Considering a graphic like this as a concise way of displaying the current workflow progress, though there are some concerns that it does not fit the style of the rest of the lifecycle slack message or that it is confusing (specifically in regard to the green representing overall job  duration and the duration of the longest job).
![Workflow](https://image-charts.com/chart?chs=500x150&cht=bhs&chd=t:35,14,253,620,0,0,0|7,0,3,150,0,0,0|0,0,0,0,14,0,0&chds=a&chg=0,2,0&chco=77A600,92CD00,D70000&chxr=200&chxt=x,y&chxl=0:|build|unit%20test|integration%20test|publish|canary%20test|staging|prod|&chof=.png)

**Comment by cdupuis** [comment]
Here's a the entire message out of the message builder:

<img width="630" alt="untitled" src="https://user-images.githubusercontent.com/206707/32384810-65b57f04-c0bc-11e7-8a90-68a9a048f683.png">

**Comment by claymccoy** [comment]
I removed the grid lines and changed the colors to match greens and reds that were already on the message. I also changed the chart width to 400px because slack will rerender if it is above that. Image is sharper now especially the fonts. What else could we do to make it look more at home?  You can play around with the slack message rendering [here](https://api.slack.com/docs/messages/builder?msg=%7B%22text%22%3A%221%20new%20commit%20to%20*%3Chttps%3A%2F%2Fr.atomist.com%2FrkwF0EJcAW%7Catomist%2Flifecycle-automation%2Fmaster%3E*%22%2C%22attachments%22%3A%5B%7B%22author_name%22%3A%22%40cdupuis%22%2C%22author_link%22%3A%22https%3A%2F%2Fr.atomist.com%2FSyuFC4k90-%22%2C%22author_icon%22%3A%22https%3A%2F%2Favatars.githubusercontent.com%2Fcdupuis%22%2C%22text%22%3A%22%60%3Chttps%3A%2F%2Fr.atomist.com%2FHy9Y041cCb%7C6b66801%3E%60%20fix%20test%20%3Awhite_check_mark%3A%20%3Chttps%3A%2F%2Fr.atomist.com%2FrJsKREJ9Cb%7CBuild%20%23118%3E%22%2C%22mrkdwn_in%22%3A%5B%22text%22%5D%2C%22color%22%3A%22%2300a5ff%22%2C%22fallback%22%3A%221%20commit%20to%20%3Chttps%3A%2F%2Fgithub.com%2Fatomist%2Flifecycle-automation%2Ftree%2Fmaster%7Catomist%2Flifecycle-automation%2Fmaster%3E%20by%20%40cdupuis%22%2C%22footer%22%3A%22%3Chttps%3A%2F%2Fr.atomist.com%2FB1YKCV1qRZ%7Catomist%2Flifecycle-automation%3E%22%2C%22actions%22%3A%5B%5D%2C%22footer_icon%22%3A%22http%3A%2F%2Fimages.atomist.com%2Frug%2Fcommit.png%22%2C%22ts%22%3A1509712826%7D%2C%7B%22color%22%3A%22%2345B254%22%2C%22fallback%22%3A%221%20successful%20check%22%2C%22actions%22%3A%5B%5D%2C%22text%22%3A%22%3Awhite_check_mark%3A%20Pre-release%20NPM%20module%20publication%20-%20%3Chttps%3A%2F%2Fr.atomist.com%2FB13tAVkq0-%7Cnpm%2Fatomist%2Fprerelease%3E%22%7D%2C%7B%22author_name%22%3A%22Tag%200.1.33-20171103124315%2Btravis.118%20created%22%2C%22author_link%22%3A%22https%3A%2F%2Fr.atomist.com%2FHy6YC4k90W%22%2C%22author_icon%22%3A%22https%3A%2F%2Fimages.atomist.com%2Frug%2Ftag-outline.png%22%2C%22fallback%22%3A%22Tag%200.1.33-20171103124315%2Btravis.118%20created%22%2C%22actions%22%3A%5B%7B%22text%22%3A%22Release%22%2C%22type%22%3A%22button%22%2C%22name%22%3A%22rug%22%2C%22value%22%3A%22creategithubrelease-0%22%2C%22confirm%22%3A%7B%22title%22%3A%22Create%20Release%22%2C%22text%22%3A%22Create%20release%20of%20tag%200.1.33-20171103124315%2Btravis.118%3F%22%2C%22ok_text%22%3A%22Ok%22%2C%22dismiss_text%22%3A%22Cancel%22%7D%7D%5D%2C%22callback_id%22%3A%22cllbck1%22%7D%2C%7B%22text%22%3A%22%60development%60%201%20started%22%2C%22author_name%22%3A%22Services%22%2C%22author_icon%22%3A%22https%3A%2F%2Fimages.atomist.com%2Frug%2Ftasks.png%22%2C%22fallback%22%3A%22%60development%60%201%20started%22%2C%22mrkdwn_in%22%3A%5B%22text%22%2C%22footer%22%5D%2C%22actions%22%3A%5B%7B%22text%22%3A%22Info%22%2C%22type%22%3A%22button%22%2C%22name%22%3A%22rug%22%2C%22value%22%3A%22cloudfoundryapplicationdetail-1%22%7D%2C%7B%22text%22%3A%22Stop%22%2C%22type%22%3A%22button%22%2C%22name%22%3A%22rug%22%2C%22value%22%3A%22stopcloudfoundryapplication-2%22%2C%22confirm%22%3A%7B%22title%22%3A%22Stop%20Application%22%2C%22dismiss_text%22%3A%22Cancel%22%2C%22ok_text%22%3A%22Proceed%22%2C%22text%22%3A%22Do%20you%20really%20want%20to%20stop%20application%3F%22%7D%7D%2C%7B%22text%22%3A%22Scale%22%2C%22type%22%3A%22button%22%2C%22name%22%3A%22rug%22%2C%22value%22%3A%22scalecloudfoundryapplication-3%22%7D%5D%2C%22ts%22%3A1509713105%2C%22footer%22%3A%22%3Chttps%3A%2F%2Fr.atomist.com%2FByRKC4yqAZ%7CFeedback%3F%3E%22%2C%22callback_id%22%3A%22cllbck2%22%7D%2C%7B%22author_name%22%3A%22Workflow%20Status%22%2C%22image_url%22%3A%22https%3A%2F%2Fimage-charts.com%2Fchart%3Fchs%3D400x130%26cht%3Dbhs%26chd%3Dt%3A35%2C14%2C253%2C620%2C0%2C0%7C7%2C0%2C3%2C150%2C0%2C0%7C0%2C0%2C0%2C0%2C14%2C0%26chds%3Da%26chco%3D0FA215%2C86DB95%2CDD5B6A%26chxr%3D200%26chxt%3Dx%2Cy%26chxl%3D0%3A%7Cbuild%7Cunit%2520test%7Cintegration%2520test%7Ccanary%2520test%7Cstaging%7Cprod%7C%26chof%3D.png%22%7D%5D%2C%22unfurl_links%22%3Afalse%2C%22unfurl_media%22%3Afalse%7D)

![screen shot 2017-11-03 at 12 11 04 pm](https://user-images.githubusercontent.com/2743/32386763-48ddf9d2-c090-11e7-90c5-85b14fbd1474.png)

**Comment by ddgenome** [comment]
We'll also have to make the rendering of the build status on the commit line smarter too, right?

**Comment by claymccoy** [comment]
I guess, it should probably refer to the workflow name and its status rather than any single build within it.

**Comment by ddgenome** [comment]
Yes, and would need to have logic around what emoji to display, red if any failed, yellow if any running, green otherwise.

**Comment by cdupuis** [comment]
There is now a icon for the workflow attachment at https://images.atomist.com/rug/flow.png.

Would be cool to add this to the screenshot @claymccoy.

**Comment by cdupuis** [comment]
@Tapppi can you review the above and let us know what you think?

**Comment by Tapppi** [comment]
Hey! Excited to see concrete progress, and I think you're going in the right direction with this.

UI looks good, I'd call that concise and informative. The chart is definitely a great way to show build times.  I'm bad at UIs so don't expect more than general directions from me on that front 😉 Thoughts:

* Build status should be fixed to represent the workflow as already mentioned
* Makes more sense to have workflow UI ordered after build status and before service status

I've had time to refine my thoughts on workflow, but things only get more complicated... 😁 

I agree that generally jobs are more important than a new abstraction on top of them, but what we are referring to as stages are more like a single job (e.g. build services, integration tests) with parallelisation. They are defined as many jobs because there is no notation to group them in to a single parallel job in Circle. Thus they could be thought of as one big job (with information about parallelisation) instead of individual jobs. Individual jobs in a "stage" can also contain parallelisation of e.g. unit tests, so these "stages" are really just a hack to model nested parallelisation.

To make things more complicated, a pipeline can have multiple parallel workflows that contain their own "stages". Or rather, an actual workflow with jobs that contain parallelisation. For example, a simplified version of our ultimate end-goal pipeline:
```
service_deps (1 job) -> build_services (20 jobs) |
job_deps (1 job)     -> build_jobs (10 jobs)     |
                        build_dashboard (1 job)  |
                                                -> dev_cluster deploy  -> WORKFLOW_END, manual usage of dev cluster
                                                -> test_cluster deploy -> integration_e2e_tests -> Canary release -> etc...

```

I haven't yet had time to think through what is a useful resolution of information and management for such a pipeline. One could mush together that example to "stages":
```
all_deps (2 job) -> all_builds (31 jobs) -> dev_test_deploy (2 jobs) -> integration_tests -> canary_release -> etc..
```

With how Circle handles only job dependencies and right now "stages" are defined as having the same upstream jobs, this technique would mean blocking the start of (potentially time-consuming) subsequent parts of the overall workflow unnecessarily, due to having to define extraneous dependencies for them to be recognised as a single stage. In the example above, one would have to define `dev_deploy`, which might take longer than spinning up a new test cluster, as an upstream job for `integration_tests`. Another interesting point is which part of this is managed by circle (builds?) and which by atomist (triggering deploys and tests?).

**Comment by cdupuis** [comment]
We shipped the initial version of this. closing.
